apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      timeouts:
        pipeline: 1h
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              storageClassName: topolvm
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
        - name: cache
          persistentVolumeClaim:
            claimName: build-cache
          subPath: yarn_cache
      taskRunSpecs:
        - pipelineTaskName: build-docs
          stepOverrides:
            - name: build
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  cpu: 4
                  memory: 8Gi
  templates:
    - templateRef:
        resolver: katanomi.dev.clustertemplate
        params:
          - name: name
            value: product-docs-pr-pipeline
      params:
        - name: doc-base
          value: servicemesh